---
title: "Sex influences the homeostatic plasma lipidome more robustly than diet or intrinsic cardiorespiratory fitness"
author: "Johanna Fleischman"
date: "2023-07-19"
update date: "`r Sys.Date()`"
output: 
  html_document:
    code_folding: hide
    toc: true
---

```{r setup, include = FALSE}
# Set up the session with necessary packages
library(tidyverse)
library(devtools) 

# Install package from github 
devtools::install_github("johanna0321/featureReduction")
library(featureReduction)

# Load data with package
data("rat_lipidomics_day0")
data("rat_lipidomics_day3")
data("rat_lipidomics_day14")
data("rat_lipidomics_group_key")
data("rat_meta_data")

knitr::opts_chunk$set(echo = TRUE, out.height='50%',out.width='50%')
```

## Make clusters

Here, I use the function reduce_features_by_pca from the package featureReduction to generate lipid clusters from my data. I perform this separately for each day of data collected.

```{r}
# Combine the 3 days of data into a list
all_rat_lipids <- list(`Day 0` = rat_lipidomics_day0,
                       `Day 3` = rat_lipidomics_day3,
                       `Day 14` = rat_lipidomics_day14)

# Perform reduce_features_by_pca on each list item using scaling (for heatmaps)
# The data provided in the package is not log2 normalized, which is performed here
all_rat_scaled_clusters <- lapply(all_rat_lipids, 
                                  function(lipid_dfs) {
                                    featureReduction::reduce_features_by_pca(feature_data = log2(lipid_dfs),
                                                           feature_group_key = rat_lipidomics_group_key,
                                                           scale = TRUE)})

# Perform reduce_features_by_pca on each list item without scaling
all_rat_norm_clusters <- lapply(all_rat_lipids, 
                                  function(lipid_dfs) {
                                    featureReduction::reduce_features_by_pca(feature_data = log2(lipid_dfs),
                                                           feature_group_key = rat_lipidomics_group_key,
                                                           scale = FALSE)})

```

## Figure 2A Heatmap

For the heatmap, we will use the scaled version of the cluster data.

```{r, warning=FALSE}

# Make heatmap cluster order
ordered_clusters <- c("AcylCN","CE","CER.mono","CER.poly","CER.sat","FFA.mono.poly",
                      "FFA.sat","GlcCER","PA","PE","PG","PI","Plas.PE","Plas.PC.sat",
                      "Plas.PC.mono","Plas.PC.poly","SM.sat","SM.mono","SM.poly",
                      "Lyso.sat","Lyso.mono","Lyso.poly","PC.sat","PC.mono","PC.poly",
                      "DG.sat","DG.mono","DG.poly","TG.sat.even","TG.sat.odd",
                      "TG.mono.even","TG.mono.odd","TG.poly.even","TG.poly.odd")

# Clean data to make data heatmap plotable, using pre-defined ordered clusters
scaled_clusts_for_heatmap <- all_rat_scaled_clusters %>% 
  dplyr::bind_rows(., .id = "Day") %>%
  dplyr::mutate(Name = substr(rownames(.),1,5)) %>%
  dplyr::relocate(Name) %>%
  dplyr::right_join(rat_meta_data, ., by = "Name") %>%
  tidyr::gather(key = "Lipid", value = "Value", -c(Name, Line, Diet, Sex, Day)) %>%
  dplyr::mutate(Lipid = factor(Lipid, levels = ordered_clusters)) %>%
  dplyr::mutate(Diet = factor(Diet, levels = c("Control","Carbohydrate","Fat"))) %>%
  dplyr::mutate(Day = factor(Day, levels = c("Day 0","Day 3","Day 14")))

# Heatmap                  
p <- ggplot(scaled_clusts_for_heatmap) +
  geom_tile(aes(fill = Value,
                y = Lipid,
                x = interaction(Name, Line, Diet, Sex))) +
  scale_fill_gradient2(low="seagreen",mid="white",high="#CC0033", midpoint=0) +
  scale_y_discrete(limits = rev(levels(scaled_clusts_for_heatmap$Lipid))) +
  theme(axis.ticks.x=element_blank(),
        strip.text = element_text(size=15),
        axis.text.x = element_text(angle=90),
        axis.text.y = element_text(size=15),
        panel.background = element_blank()) + 
  labs(fill="Z-score") +
  facet_wrap(~scaled_clusts_for_heatmap$Day, nrow = 1, ncol = 3)  
print(p)

```